msrv = "1.88"

doc-valid-idents = [
    "..",
    "ACU",
    "Nubster",
    "MnemoDB",
    "EidosDB",
    "ThemisDB",
    "StyxDB",
    "AEIF",
    "SOAG",
    "GitHub",
    "PostgreSQL",
    "SQLite",
]
